medooze/media-server-node

- package.json
You'll see this error for both package and dist scripts
> sh: 1: [: Linux: unexpected operator
For any shell commands run inside package.json scripts apparently uses specifically /bin/sh (not bash), and both [ and test require to use = for equivalence, not ==.
> Minor /bin/sh fix

- binding.gyp
Enforces symbol resolution inside media-server-node shared object, avoids conflicts with openssl shipped within node
> Flag on linux to external build, enforces symbol resolution

- manual.md
I think that tutorial for setting up an endpoint manually could be simplified a bit trough using `MediaServer.getDefaultCapabilities()` method when generating answer instead of plain object.
I could hardly imagine a situation when developer would want to provide a set of server capabilities different from a default one.
> Tutorial: simplify answer creation code

- package.json
This reduces the number of packages installed for a simple project considerably, from ~250 to ~8 and reduces the `node_modules` size by about 100MB.
> Move tap test framework to devDependencies

- medooze-media-server.d.ts
`createEndpoint` now accepts multiple IPs. This fixes the typings to reflect that
> Update createEndpoint type definition

- binding.gyp
The build currently fails on arm64 platforms. This PR fixes it.
> Include crc32 config file on arm64 targets

- external/srtp/aes_gcm_ossl.c
- external/srtp/libsrtp.gyp
this patches the OpenSSL backend that comes with libsrtp to avoid 2 operations that go through the OSSL_PARAMS API and cause significant overhead:
- initializing context with IV (`EVP_CipherInit_ex`)
- getting / setting the tag (`EVP_CIPHER_CTX_ctrl` with `EVP_CTRL_GCM_GET_TAG` / `EVP_CTRL_GCM_SET_TAG`)
these operations are replaced with code that sets the fields directly into OpenSSL's internal struct. this means we need to hardcode a bunch of offsets that could change from one version to the other. I've attached a command to consult such offsets (must be ran at the root of an OpenSSL clone at the appropriate version).
it also removes a workaround that sets a bogus auth tag when decrypting.
such workaround is no longer needed in OpenSSL 3.
together, these 3 changes cancel the extra …
> libsrtp AES-GCM OpenSSL backend: bypass OSSL_PARAM

- lib/IncomingStream.js
- lib/IncomingStreamTrack.js
- lib/IncomingStreamTrackMirrored.js
- lib/IncomingStreamTrackReader.js
- lib/IncomingStreamTrackSimulcastAdapter.js
- lib/OutgoingStream.js
- lib/Recorder.js
- lib/SharedPointer.js
- lib/Transport.js
SharedPointer has an automagical system that wraps most native functions in a proxy that does `SharedPointer()` for you.
This is nice, but for now it's hard to make the type system aware of this, so I'd like to reintroduce the calls to SharedPointer even if they don't do anything (consider them annotations like #217).
> reintroduce SharedPointer calls

- lib/ActiveSpeakerDetector.js
- lib/ActiveSpeakerMultiplexer.js
- lib/Endpoint.js
- lib/IncomingStream.js
- lib/IncomingStreamTrack.js
- lib/IncomingStreamTrackMirrored.js
- lib/IncomingStreamTrackReader.js
- lib/IncomingStreamTrackSimulcastAdapter.js
- lib/OutgoingStream.js
- lib/OutgoingStreamTrack.js
- lib/PeerConnectionServer.js
- lib/Player.js
- lib/Recorder.js
- lib/RecorderTrack.js
- lib/Refresher.js
- lib/SDPManager.js
- lib/Transponder.js
- lib/Transport.js
this is what we did in https://github.com/medooze/srt-server-node/pull/43#issuecomment-1723112825.
when we add type annotations (#217) these event blocks are converted to a central `@typedef` at the top of the file, i.e:
https://github.com/medooze/media-server-node/blob/fae10185b2f9e664c06c7b039a0dfb0a0e1033ee/lib/Transport.js#L63-L73
i would like to delete the jsdoc blocks because:
- many of them are outdated or just incorrect
- i'd prefer having a single source of truth
- the new syntax is more compact, yet allows expressing the same info
- the new syntax is actually **enforced** by typechecking, which ensures we'll keep it up to date, and it also helps users
- in the future we can switch to [typedoc](https://typedoc.org) to render our documentation, and it will make this info visible …
> remove jsdoc event blocks

- lib/ActiveSpeakerDetector.js
- lib/ActiveSpeakerMultiplexer.js
- lib/EmulatedTransport.js
- lib/Endpoint.js
- lib/IncomingStream.js
- lib/IncomingStreamTrack.js
- lib/IncomingStreamTrackMirrored.js
- lib/IncomingStreamTrackReader.js
- lib/IncomingStreamTrackSimulcastAdapter.js
- lib/MediaServer.js
- lib/Native.js
- lib/NetworkUtils.js
- lib/OutgoingStream.js
- lib/OutgoingStreamTrack.js
- lib/PeerConnectionServer.js
- lib/Player.js
- lib/Recorder.js
- lib/RecorderTrack.js
- lib/Refresher.js
- lib/SDPManager.js
- lib/SDPManagerPlanB.js
- lib/SDPManagerUnified.js
- lib/SharedPointer.js
- lib/Transponder.js
- lib/Transport.js
- lib/Utils.js
finally, after #216 I think I have everything ready to add / fix the JSDoc comments on the code.
I'm pretty happy with the results, very very few errors remain ^^
and I found many typos along the way (#215)
the rationale is the same than for https://github.com/medooze/semantic-sdp-js/pull/28. our current typings are so outdated they're likely misleading people at this point rather than helping. so, delete them and autogenerate them from the JSDoc comments in our code.
**not ready for review yet.** there are still some things I'd like to take out of this PR first, to ease review (a bugfix and some needed refactors)
> add / fix JSDoc annotations

- lib/Endpoint.js
the code to parse a PeerInfo into a ParsedPeerInfo is copy-pasted 2 times.
this also fixes the type errors.
> deduplicate parsing PeerInfo

- lib/IncomingStreamTrack.js
- src/RTPIncomingSource.i
- src/RTPSource.i
- src/media-server.d.ts
- src/media-server_wrap.cxx
If VLA is used with a single layer stream with no layer info (for example an h264 stream), a new `LayerSource` was created for storing the target bitrate/width/heigh/fps, but it was not used for calculating the other stats
So when the stats where gathered, as there was already a single layer, the code to create a default layer for the source if no layer info was present, was not run, and therefore the bitrate field was not exposed correctly.
With the change on the media server, we are adding the target stats to the `RTPIncomingSource` as well and not creating a `LayerSource`.
This PR exposes the target stats at source level and so the `getActiveLayers()` provide the correct info.
> Fix available layers stats when VLA is used with a single/default layer

- lib/Transport.js
calling `transport.dump()` and then `transport.stopDump()` currently causes C++ to print a "not dumping" error if only BWE was requested in the call to dump():
~~~
[61519 VIEW4     ][1701274443.460][ERR]-DTLSICETransport::StopDump() | Not dumping
~~~
this is currently spamming our logs a bit. so, have Transport track state and avoid unnecessary C++ calls.
an alternative is to remove the C++ Error() log line.
> prevent "not dumping" C++ errors

- lib/Transponder.js
the Transponder listens for `encoding` events on the assigned track. if an encoding with the same ID as the current one is emitted, it will re-select it by calling `selectEncoding()` again:
https://github.com/medooze/media-server-node/blob/91226d64cde3109d59be80233920acbc8c6d0242/lib/Transponder.js#L84-L89
this doesn't work in practice because the first thing `selectEncoding()` does is reject calls for the same encoding ID as the currently stored one:
https://github.com/medooze/media-server-node/blob/91226d64cde3109d59be80233920acbc8c6d0242/lib/Transponder.js#L637-L642
I understand we're doing this to avoid unnecessary calls to C++, so instead of checking for a change in encoding ID, we should check for a change in the encoding object itself or in the RTP sources directly. I've opted for …
> fix Transponder encoding re-selection

- lib/Endpoint.js
- lib/PeerConnectionServer.js
This opens up the override options needed to to disabling e.g. REMB (disableREMB) as a CreateTransportOptions is misssing when creating the PeerConnectionServer
Handles issue from #240
> Add CreateTransportOptions to PeerConnectionServer constructor

- lib/IncomingStream.js
- lib/IncomingStreamTrack.js
- lib/IncomingStreamTrackSimulcastAdapter.js
- lib/OutgoingStreamTrack.js
- lib/Transport.js
bunch of small fixes in the JSDoc comments I had pending to push for some weeks.
- first, do not use `@deprecated` for `@property` annotations since TypeScript doesn't yet support them, and they break the whole comment parsing.
- then, fix some typos.
> jsdoc annotation fixes

- lib/IncomingStreamTrack.js
- src/RTPIncomingSourceGroup.i
- src/media-server.d.ts
to my knowledge the 'remb' property on incoming encoding stats has never worked since it was added at d469b6f, but I guess better late than never 😅
(I don't think we're using this ourselves, we never do REMB when receiving AFAIK)
> fix reported REMB stat

- lib/IncomingStreamTrack.js
- lib/IncomingStreamTrackMirrored.js
- lib/IncomingStreamTrackSimulcastAdapter.js
- tests/incomingstreamtracksimulcastadapter.js
this mimics the event we send when a track is removed from a stream
> Add encodingremoved event to IncomingStreamTrackSimulcastAdapter when track is removed

- lib/IncomingStreamTrackSimulcastAdapter.js
fixes a little flaw of #257.
when SimulcastAdapter emits encodingremoved for a certain encoding, it is still present in `this.encodingsPerTrack`, meaning it is still reflected in `getActiveLayers()`. to be safe, defer event emitting until the track removal is done.
> SimulcastAdapter: wait for track to be fully removed before emitting encodingremoved

- .github/workflows/publish.yml
- package.json
Diff between packages is npm adds licenses and readme's, and removes .git config:
Sample publishing job:
https://github.com/medooze/media-server-node/actions/runs/9036679574/job/24834054462
> Use npm pack and Github Actions to publish releases to npmjs

- lib/ActiveSpeakerDetector.js
- lib/ActiveSpeakerMultiplexer.js
- lib/EmulatedTransport.js
- lib/Endpoint.js
- lib/IncomingStream.js
- lib/IncomingStreamTrack.js
- lib/IncomingStreamTrackMirrored.js
- lib/IncomingStreamTrackSimulcastAdapter.js
- lib/MediaServer.js
- lib/OutgoingStream.js
- lib/OutgoingStreamTrack.js
- lib/Recorder.js
- lib/SDPManagerUnified.js
- lib/SharedPointer.js
- lib/StreamerSession.js
- lib/Transponder.js
- lib/Transport.js
- lib/Utils.js
- package.json
most of this is just fixing type errors (I'd like to start enforcing typechecking in CI, since it would have caught bugs such as [this one](https://github.com/medooze/media-server-node/commit/7433637116a6c7107df47b02ef467a7b46b887cb))
but there's also a couple bugfixes.
I suggest reviewing commit by commit.
> type fixes and some bugfixes

- lib/IncomingStreamTrack.js
- lib/IncomingStreamTrackMirrored.js
- lib/OutgoingStream.js
- lib/Transport.js
- package.json
- src/DTLSICETransportListener.i
- src/RTPOutgoingSourceGroup.i
- src/media-server_wrap.cxx
This PR adds support for detecting unsignaled sources that provides relevant `mid` and `rid` values.
The `mid` is used for selecting the track to associate the id, and the `rid` for the source id. RTX ssrc is associated by `rid` or `rrid` afterwards.
> feat: add support for unsignaled sources

- lib/Endpoint.js
- package.json
- tests/endpoint.js
This PR allows using the new `unified` option in semantic-sdp for using unified plan mids.
https://github.com/medooze/semantic-sdp-js/pull/41/
> update min semantic-sdp version

- lib/IncomingStreamTrack.js
- lib/IncomingStreamTrackSimulcastAdapter.js
- lib/Transponder.js
- tests/transponder.js
This PR allows to specify the codec preferences in order to choose the correct layer.  It will allow us to implement multi video codec simulcast and only use the layers that the client supports for layer switching.
> feat: allow specifying codec preferences on setTargetBitrate()
